# -*- coding: utf-8 -*-
"""Arduino PIR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iieRx_3B0S5Mleur_PM2LrFLQA7KbXLG
"""

int led_pin = 13;
int buz_pin = 12;
int pir_pin = 8;

void_setup(){
    Serial.begin(9600);
    pinMode(led_pin, OUTPUT);
    pinMode(buz_pin, OUTPUT);
    pinMode(pir_pin, INPUT);

}

void_loop(){
    int out == digitalRead(pir_pin);
    if(out == 1){
        digitalWrite(led_pin, HIGH);
        digitalWrite(buz_pin, HIGH);
        Serial.println("Motion Detected");
    }
    else{
        digitalWrite(led_pin, LOW);
        digitalWrite(buz_pin, LOW);
        Serial.println("No Motion Detected");
    }
}